package repository.model.entity.enums;

public enum MedicalWardType {

    ALLERGOLOGY,
    ANESTHESIOLOGY_AND_RESUSCITATION,
    BACTERIOLOGY_AND_MICROBIOLOGY,
    INTERNAL_DISEASES,
    CARDIOLOGY,
    DENTAL_MEDICINE,
    DEPARTMENT_OF_PEDIATRICS,
    DERMATOLOGY,
    EAR_NOSE_THROAT,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GENERAL_SURGERY,
    GYNECOLOGY,
    HEMATOLOGY,
    INFECTIOUS_DISEASES_AND_CLINICAL_MICROBIOLOGY,
    NEUROLOGY,
    NEUROSURGERY,
    OPHTHALMOLOGY,
    ORTHOPEDY,
    PHYSIOTHERAPY_AND_REHABILITATION,
    PSYCHIATRY,
    PSYCHOLOGY,
    UROLOGY
}
